# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = []
cloned_from = "upbSFtTuSTKsxatqvpJFr4"
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "rust"
manifest_version = 3
name = "Default starter for Rust"
service_id = "upbSFtTuSTKsxatqvpJFr4"
